apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: factura-mysql-pvc
  namespace: demo
spec:
  accessModes:
    - ReadWriteOnce
  resources:
    requests:
      storage: 2Gi
---
apiVersion: apps/v1
kind: Deployment
metadata:
  name: factura-mysql
  namespace: demo
spec:
  replicas: 1
  selector:
    matchLabels:
      app: factura-mysql
  template:
    metadata:
      labels:
        app: factura-mysql
    spec:
      volumes:
        - name: data
          persistentVolumeClaim:
            claimName: factura-mysql-pvc
      containers:
        - name: mysql
          image: mysql:8.0.30
          env:
            - name: MYSQL_ALLOW_EMPTY_PASSWORD
              value: "yes"
            - name: MYSQL_DATABASE
              value: factura
          args:
            - --lower_case_table_names=1
            - --skip-ssl
            - --character_set_server=utf8mb4
            - --explicit_defaults_for_timestamp
          ports:
            - containerPort: 3306
          volumeMounts:
            - name: data
              mountPath: /var/lib/mysql/
          resources:
            requests:
              memory: "512Mi"
              cpu: "500m"
            limits:
              memory: "1Gi"
              cpu: "1"
---
apiVersion: v1
kind: Service
metadata:
  name: factura-mysql
  namespace: demo
spec:
  selector:
    app: factura-mysql
  ports:
    - port: 3306
