commonLabels:
  app.kubernetes.io/genereted-by: JHipster

namespace: demo

resources:
  - namespace.yml
  # Individual apps
  - gateway-k8s/gateway-deployment.yml
  - gateway-k8s/gateway-service.yml
  - gateway-k8s/gateway-postgresql.yml
  - factura-k8s/factura-deployment.yml
  - factura-k8s/factura-service.yml
  - factura-k8s/factura-mysql.yml
  - cliente-k8s/cliente-deployment.yml
  - cliente-k8s/cliente-service.yml
  - cliente-k8s/cliente-mongodb.yml
  # service discovery eureka/consul
  - registry-k8s/consul.yml
  - registry-k8s/consul-config-loader.yml
  - registry-k8s/application-configmap.yml

patchesJson6902:
